# Fundamentos en Python
## Listas, Slicing, Tuplas, Funciones, Paquetes, Numpy y Arreglos

Una lista es como un arreglo, (en R una lista es como un vector)
Lista es una secuencia ordenada de elemntos, ordenados. La numeracion comienza en 0 [*R En R la numeración empieza en 1*]

Listas: **tipos de Datos Mixtos** podemos tener listas con diferentes tipos de datos en la misma lista
Listas: se usan [] para los eltos de la lista.
rango --> range()

In [8]:
miLista = [1,2,3,4,5,6]
print(miLista)

[1, 2, 3, 4, 5, 6]


In [10]:
listaMixta = ["Hola", True, 55.3,24]
print(listaMixta)

['Hola', True, 55.3, 24]


---


In [15]:
#FUNCIONES
#generador de listas con range, desde 0 hasta 15(sin incluiye el 15)
list(range(0,15)) 


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [37]:
list(range(0,15,2))  #genera desde 0 a 15 con salto de 2 en 2


[0, 2, 4, 6, 8, 10, 12, 14]

In [61]:
L3 = list(range(100,210,10))

In [63]:
L3

[100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

---

### Acceder a los datos de una lista

In [74]:
vocales = ["a", "e","i","o","u"]
#           0    1   2   3   4 
#negativa  -5   -4  -3   -2  -1
vocales[2]


'i'

In [76]:
vocales[-4]

'e'

In [78]:
len(vocales) #contar los eltos de una lista

5

In [82]:
#cambiar eltos de una lsita
vocales[2] = "b"
vocales

['a', 'e', 'b', 'o', 'u']

In [ ]:
#SLICING - TOMAR UN SUBSET DE ELTOS DE UNA LISTA, PORCIONES
#USA LOS : PARA indicar (donde empieza):(donde acaba):(salto)

In [86]:
letras = ['a','b','c','d','e','f','g','h','i','j']
#posiciones0   1   2   3   4   5   6   7   8   9 


In [88]:
letras[2:]

['c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [90]:
letras[2:5]

['c', 'd', 'e']

In [92]:
letras[2::2] #empieza en 2 hasta el final(no pongo dato) y salto de 2 en 2

['c', 'e', 'g', 'i']

In [100]:
letras[::-1] #le da la vuelta a la lista, invierte toda la lista

['j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

---

# TUPLAS
Es una lista **inmutable** de elementos
se crea con ( ) en vez de []

In [108]:
tupla = (1,2,3,4,5,6,7)
tupla[2]


3

In [110]:
tupla[2] = 5

TypeError: 'tuple' object does not support item assignment

In [ ]:
#error porque no deja cambiar  tuple' object does not support item assignment

---

<h2>FUNCIONES </h2>
funciones en Python//Paquetes en Python: tienen varias funciones

<span style="color:blue">Modulo:</span> un archivo que contiene def, func, y declaraciones de Python <br><span style="color:blue">Paquete:</span> relaciona diferentes modulos en una misma estructura, hay pquetes muy completos con cientos de modulos

In [123]:
#Paso 1: ENCONTRAR PAQUETE:--> **GITHUB**
#Paso 2: INSTALAR EL PAQUETE: win: desde el comand prompt (anaconda) -->conda install nombrepaquete  
# O sino (vscode): pip instal nombrepaquete
#Paso 3: IMPORTAR PAQUETE :  import paquete // from paquete.modulo import modulo

In [1]:
import scrapy

In [7]:
from scrapy.crawler import CrawlerProcess

---

<h2>ARRAYS O ARREGLOS </h2>

SE usa mucho el paquete **numpy** para arrays

Un array no puede tener diferentes tipos de datos, no es mixto, convierte los datos a texto si hay un string dentro 

In [11]:
import numpy as np #para llamarmo np en vez de numpy y ahorrar texto


In [13]:
#creamos una lista que luego pasaramos a numpy para crear el array

In [19]:
L = [2345,54,1028,32,64,8,16]
a = np.array(L)
print(a)

[2345   54 1028   32   64    8   16]


In [22]:
M = [12, 5, "b", True ]
b = np.array(M)
print(b)

['12' '5' 'b' 'True']


Ha convertido todos los eltos de la lista a string, los números y el True es un string. 

In [25]:
L.pop() #escribimos L. y pulsamos tab para ver los metodos disponibles.

16

In [35]:
a.mean()


2345

In [37]:
a.argmin()

5

In [41]:
a.max()

2345

<h3>Slicing en Array</h3>

In [48]:
#similiar al slicing en listas, no estamos creando copias del array, solo crea una vista
a[2:4]

array([1028,   32])

In [50]:
b = a[2:4]
print(b)

[1028   32]


In [52]:
#modificaciones sobre esos trozos slicing de array se modifica el array original
b[:] = 45 #cambiamos todos los elementos del array b por el numero 45
print(b)

[45 45]


In [54]:
print(a)

[2345   54   45   45   64    8   16]


In [56]:
#tambien ha camabiado el array a 
#Para crear una copia hay que usar el mtd copy 
c= a.copy()
print(c)


[2345   54   45   45   64    8   16]


In [58]:
c[0:4] = 666

In [62]:
print("El array original es a:",a)
print("El array que es copia de a y ha sido cambiado es c: ", c)

El array original es a [2345   54   45   45   64    8   16]
El array que es copia de a y ha sido cambiado es c:  [666 666 666 666  64   8  16]
