# MATRICES

Una matriz es una lista de 2 dimensiones, tabla: fila x columnas 
Indexación: A[2,3] matriz A [fila2, columna3]

**La indexación comienza en 0**
indexación fila completas: [0,:] <--todos los eltos de la fila 0
o columnas completas [:,3] <-- todos los eltos de la columna 3

    |     || [:,0]| [:,1] | [:,2] |
    |-----||------| ----- |-------|
    |[0,:]||  0,0 |  0,1  |  0,2  |
    |[1,:]||  1,0 |  1,1  |  1,2  |
    |[2,:]||  2,0 |  2,1  |  2,2  |

In [ ]:
#usamos los datos del 04-setDatos notebook

In [32]:
import numpy as np

In [34]:
# de varias listas las pasamos a un array y así se crea una matriz
# ejemplo: ver en 04-setDatos 
#sueldo = np.array([jugador1_sueldo, jugador2_sueldo, juegador3_sueldo,... ])
#cada jugadorx_sueldo es una lista con datos, y al pasarlo a np.array creamos un array que es sueldo


Creamos una matriz con **np.reshape(a, newshape, order='C')** tambien se puede poner sin order = , poniendo solo la 'C' (que pertenece a numpy)
reshape reorganiza los eltos de un array

*Parámetros*:

    *a: el vector de numpy que se desea redimensionar.
    *newshape: una tupla, es la dimensión, se da el detalle de (filas, columnas)
    *order: indica como se llenan los vectores, puede ser 'C'(estilo lenguaje C por filas), 'F'(estilo Fortran por columnas), 'A'(según como se tenga en memoria)      

|

Sino se da parámetro C o F se rellena por filas  de manera por defecto, al contrario que en R-->

Otro método **es np.arra**y() donde se rellena por filas

In [45]:
import numpy as np
mis_datos = np.arange(0,20)
print(mis_datos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [49]:
#vamos a dar forma a esos datos creados en lista
np.reshape(mis_datos,(5,4))  #las dimensiones se pasan como una tupla, (5,4) indica 5 filas y 4 columnas
#CUIDADO -el default es opuesto a R

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [107]:
matriz_C = np.reshape(mis_datos, (5,4), 'C')
print("\033[44m Matriz C\033[0m")
print("\033[1;34m")
print(matriz_C,"\033[0m")

 Matriz C

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 


In [105]:
matriz_F = np.reshape(mis_datos, (5,4), 'F')
print("\033[42m Matriz F\033[0m")
print("\033[1;32m")
print(matriz_F,"\033[0m")

 Matriz F

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] 


In [75]:
#ejercicio llegar al nº9 en cada matriz
matriz_C[2,1]

9

In [73]:
matriz_F[4,1]

9

In [127]:
#CONCEPTO POO (programación orientado a objetos)
#np.reshape(mis_datos,(5,4)) en vez de esto podemo usar:
type(mis_datos)  #vemos que es array

numpy.ndarray

In [133]:
mis_datos.reshape(5,4)  #POO

#en vez de dar los datos dentro del reshape se usa POO usando mis_datos.metodo(reshape)
#(esto se ve si escribimos mis_datos. y damos a tab para ver los métodos disponibles)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

---

In [136]:
#agregamos unas listas
r1 = ["Soy","muy","feliz"]
r2 = ["Que","gran","día"]
r3 = [1,2,3]

In [138]:
#lista dentro de listas
[r1,r2,r3]

[['Soy', 'muy', 'feliz'], ['Que', 'gran', 'día'], [1, 2, 3]]

In [142]:
#aplicamos np.array para combinarlas y hacer una matriz
np.array([r1,r2,r3])

array([['Soy', 'muy', 'feliz'],
       ['Que', 'gran', 'día'],
       ['1', '2', '3']], dtype='<U11')

In [144]:
print(np.array([r1,r2,r3]))  #si ponemos print ya no sale el dato dtype='<U11' al final de la matriz

[['Soy' 'muy' 'feliz']
 ['Que' 'gran' 'día']
 ['1' '2' '3']]


In [ ]:
#En los array solo podemos tener un tipo de datos por fila