# DICCIONARIOS

Cuando usamos matrices grandes, como en el caso de los dtos del 04-SetDatos.ipynb de los datos de jugadores NBA:

Los diccionarios se crean con {} 

diccionario1 = {'clave1':'valor1','clave2':'valor2','clave3':'valor3'}

Los diccionarios son como listas de elementos no ordenados
Para acceder a sus elementos se usan las claves (etiqueta)

In [12]:
#lo primero importamos el numpy para trabajar con los datos
import numpy as np

In [16]:
#en el caso de los datos de juegos:
#Juegos 
KobeBryant_j = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_j = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_j = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_j = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_j = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_j = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_j = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_j = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_j = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_j = [75,51,51,79,77,76,49,69,54,62]
#Matrix
juegos = np.array([KobeBryant_j, JoeJohnson_j, LeBronJames_j, CarmeloAnthony_j, DwightHoward_j, ChrisBosh_j, ChrisPaul_j, KevinDurant_j, DerrickRose_j, DwayneWade_j])


In [18]:
print(juegos)

[[80 77 82 82 73 82 58 78  6 35]
 [82 57 82 79 76 72 60 72 79 80]
 [79 78 75 81 76 79 62 76 77 69]
 [80 65 77 66 69 77 55 67 77 40]
 [82 82 82 79 82 78 54 76 71 41]
 [70 69 67 77 70 77 57 74 79 44]
 [78 64 80 78 45 80 60 70 62 82]
 [35 35 80 74 82 78 66 81 81 27]
 [40 40 40 81 78 81 39  0 10 51]
 [75 51 51 79 77 76 49 69 54 62]]


In [22]:
#Para buscar el ultimo dato de jugador CarmloAntony 
#CarmeloAnthony_j = [80,65,77,66,69,77,55,67,77,40]
#había que saber que sus datos son la fila 3 de la matriz juegos
#y el último dato lo localizamos con la indexación negativa
print(juegos[3,-1])

40


 cada fila es un jugador y para buscar un dato de un jugaador tendriamos que saber que posición ocupa en la matriz 
y luego saber que dato queremos en qué columna se encuentra, para evitar esto usamos **DICCIONARIOS**
En R sí que tienen columnas con nombres y se pueden asignar a los jugadores, en este caso, y es más facil.


---

In [27]:
diccionario1 = {'clave1':'valor1','clave2':'valor2','clave3':'valor3'}

In [32]:
diccionario1['clave2']

'valor2'

In [34]:
dicc2 ={'Chile':'Valor chile','España':'€','Colombia':500}
#pueden tener diferentes tipos de datos

In [40]:
dicc2['España']

'€'

In [42]:
#En el setData tenemos 2 diccionarios, el dic_temp que nos asigna un valor a cada año y dic_jug que asigna una fila a cada jugador
#Temporadas
temporadas = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
dic_temp = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Jugadores
jugadores = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
dic_jug = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}


In [44]:
#posicion  de la temporada 2008?:
print(dic_temp['2008']) 


3


In [ ]:
#así sabemos que en la posicion 3 está la temporada buscada

In [46]:
print(dic_jug['KobeBryant'])

0


In [48]:
#Sabiendo ya que el jugador tiene la fila 0 y la temporada es la 3:
juegos[0,3]


82

In [50]:
juegos[dic_jug['DerrickRose'],dic_temp['2006']]  #combinamos la buscada indexada de jugador y temporada usando diccionarios

40

In [68]:
juegos[dic_jug['DwightHoward']][dic_temp['2012']]  #tambien se puede poner así juegos[][]
#juegos[4][7]  # es igual que juegos[4,7]

76

In [ ]:
#como en python las matrices no tienen nombre de filas o columnas se usan dicc para asignar nombres para su busqueda